theme: jekyll-theme-slate
# Dependencies
markdown:         kramdown

gems: 			  [jekyll-paginate, jekyll-gist]

# Setup
title:            Tech On Boats
tagline:          'Building cool tech for boats'
description:      'Ruby, Javascript, Crystal, Mobile, Web, Server and IoT applications'
url:              http://damianham.github.io

author:
  name:           'Damian Hamill'
  url:            https://twitter.com/damianham

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/damianham
